### ISSUE TITLE
Remove clients once they are off my caseload?

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#10]
How can we remove clients once they are off my caseload?
 
Criminal Justice Services-spot-vert
Kenia Cluff
Probation Case Manager

**Comment by kuanb** [comment]
Clients should never be removed perhaps but only turned "off"

**Comment by kuanb** [comment]
Do we need to account for OTN overlap? I dont think so for now... maybe we just roll with the clients being separate and not having to be unique

**Comment by bpdesigns** [comment]
Okay for now I think. We have heard that people use aliases. If we can account for OTN overlap in the future and flag when that happens its a bonus.

**Comment by kuanb** [comment]
Resolved via https://github.com/slco-2016/clientcomm/commit/7fed466161803adc237e50b212bddc401820e4e4
