### ISSUE TITLE
Notification card. Refinement of time selections

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#103]
@kuanb On the notification dropdowns for time, what about doing hours from 1-12 on one drop down and am/pm on the second instead of 1-24 and 15-30? I've a hunch that notifications don't need to be that specific in fractions of an hour.

**Comment by kuanb** [comment]
So just by the hour, no use of the 30 minute section, and swap that to AM/PM?
Seems fine to me.

**Comment by kuanb** [comment]
This is a mild tweak on the back end as well... What I will do is prob tackle this when I get back to SF, and in the meantime we can also see if anyone actually uses the 30 min increments (I agree might be over doing it)

**Comment by bpdesigns** [comment]
Sounds good.

Ben Peterson
Designs & Strategy <http://benpetersondesigns.com/>
LinkedIn <https://www.linkedin.com/in/benpetersondesign>
@bpdesign <https://twitter.com/bpdesign>

**Comment by kuanb** [comment]
this was implemented
