### ISSUE TITLE
Case managers need to allow another case manager or admin to access their account

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#108]
Case managers need to allow another case manager or admin to access their account in an emergency in order to respond timely to clients messages.

OR 

Case managers need to be able to set an out of office message and alternative contact so that   clients know their case manager is away and have another Criminal Justice Services staff member to connect with.

**Comment by bpdesigns** [comment]
1. decide on which approach (B/K)
2. create a u/x flow  (B)
3. review  (B/K)
4. implement (K)

**Comment by kuanb** [comment]
General notion is to go with method #2.

Allow admins to send out an "alert" to a case manager's clients.

**Comment by kuanb** [comment]
"Case managers need to be able to set an out of office message and alternative contact so that clients know their case manager is away and have another Criminal Justice Services staff member to connect with."

**Comment by kuanb** [comment]
V4 permissions structure allows for this.
