### ISSUE TITLE
Color groups - main page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#112]
current main page with gray hover bar on red client:
![screen shot 2016-07-25 at 11 05 28 pm](https://cloud.githubusercontent.com/assets/15329140/17126705/d692afd6-52bc-11e6-9039-49f0582c7d96.png)

original design idea for hover bar matching color group:
![screen shot 2016-07-25 at 11 07 48 pm](https://cloud.githubusercontent.com/assets/15329140/17126721/f0b8faaa-52bc-11e6-886e-041341697a8e.png)

Note: please make the vertical color pill slimmer to match original design

**Comment by bpdesigns** [comment]
@kuanb please review today. Relates to demoing functionality

**Comment by kuanb** [comment]
c5d52c8..e0720a7 resolves
