### ISSUE TITLE
notification page small text style edit to match main page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#115]
main page
![screen shot 2016-07-25 at 11 23 58 pm](https://cloud.githubusercontent.com/assets/15329140/17126930/e77a3164-52be-11e6-8e67-535015112af5.png)

notification page
![screen shot 2016-07-25 at 11 23 01 pm](https://cloud.githubusercontent.com/assets/15329140/17126938/ed716dd0-52be-11e6-8324-4517acd10961.png)

differences in size of font and white bar behind text

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/17161163/ff81e2ce-535f-11e6-8231-b2442d8b0fac.png)

**Comment by kuanb** [comment]
hrmm...
let me know if this issue continues

**Comment by kuanb** [comment]
i dont see it on my computer... perhaps has been resolved? re-open if not when new version loaded online

**Comment by kuanb** [comment]
o wait i figured out what was going on

![image](https://cloud.githubusercontent.com/assets/6053396/17161571/75852622-5363-11e6-8059-d2bbe6365189.png)


now really is fixed
