### ISSUE TITLE
template - card page edits 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#116]
Hi Kuan here are my thoughts on making this easier for case managers 

1. Make subject mandatory
![screen shot 2016-07-25 at 11 29 31 pm](https://cloud.githubusercontent.com/assets/15329140/17127039/bed7a8da-52bf-11e6-9689-002add35f340.png)

2. Make button to "select template" always visible
![screen shot 2016-07-25 at 11 28 47 pm](https://cloud.githubusercontent.com/assets/15329140/17127064/ed5c7e92-52bf-11e6-9585-668152d65333.png)
instead of 
![screen shot 2016-07-25 at 11 28 47 pm](https://cloud.githubusercontent.com/assets/15329140/17127060/e9c2fb44-52bf-11e6-90b9-f0e2ca231baf.png)

3. I would remove the dropdown section "Limit template to specific client (or all clients)"

![screen shot 2016-07-25 at 11 27 55 pm](https://cloud.githubusercontent.com/assets/15329140/17127067/ffef81d0-52bf-11e6-9022-2683378feb7d.png)

In terms of having certain templates for individual clients vs all clients, my thought is instead to have all templates visible from the main page only. I think its more confusing to having some templates accessible under some clients but not others. I was thinking that there would not be template pages associated with individual clients.

Happy to discuss the logic of having notifications to specific clients with you tomorrow

**Comment by bpdesigns** [comment]
@kuanb please review this today. Relates to the demo tomorrow.

I would remove the dropdown section "Limit template to specific client (or all clients)"

screen shot 2016-07-25 at 11 27 55 pm

In terms of having certain templates for individual clients vs all clients, my thought is instead to have all templates visible from the main page only. I think its more confusing to having some templates accessible under some clients but not others. I was thinking that there would not be template pages associated with individual clients.

**Comment by kuanb** [comment]
grey out or disable button instead of hide at first

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/17161141/cf78550e-535f-11e6-857e-19635cbc6244.png)


got rid of specifying clients

as for button grey out, need to create a new issue for that specifically
