### ISSUE TITLE
create new template text field updates 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#119]
![screen shot 2016-07-25 at 11 27 52 pm](https://cloud.githubusercontent.com/assets/15329140/17127328/0453961a-52c2-11e6-884a-a44a7d96686a.png)
1. Can we add a subject form field line to the template?
2. Can we limit the text fill to be 160 characters?

**Comment by kuanb** [comment]
2 solved

**Comment by kuanb** [comment]
and 1
