### ISSUE TITLE
Template page - Clickable rows

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#120]
At the moment there doesn't seem to be way to access a template message in order to use it. 

IDEA: make each row clickable to launch the template its associated with.

**Comment by kuanb** [comment]
Is this from the template view as opposed to being from the template select view card?

**Comment by kuanb** [comment]
I believe it is and have proceeded as such....

**Comment by bpdesigns** [comment]
@kuanb yes.

**Comment by kuanb** [comment]
this has been resolved in latest ~4 commits
