### ISSUE TITLE
templated message page - styling 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#122]
instead of making the boxes for each template a fixed height, let the amount of text in the template message dictate the height.

![screen shot 2016-07-25 at 11 56 22 pm](https://cloud.githubusercontent.com/assets/15329140/17127531/7f3f6916-52c3-11e6-9c8f-95d9d1791fcb.png)

**Comment by kuanb** [comment]
ok. this is in contradiction to what we said yesterday. 

but i think / agree it is the right direction. i am implementing a max height, though, so that long messages do not become unwieldly

**Comment by bpdesigns** [comment]
@kuanb there must have been a miscommunication, this is what I meant.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/17158660/b4150838-534c-11e6-9421-2db6abdb453e.png)
 gotcha ben then my bad

either way i think it is better method :)

**Comment by kuanb** [comment]
dd2848b..4f6971d resolves
