### ISSUE TITLE
template main page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#127]
![screen shot 2016-07-26 at 10 34 09 pm](https://cloud.githubusercontent.com/assets/15329140/17163976/1e49cc5a-5381-11e6-8919-3197a70ff4c3.png)

Please remove "specific clients" from this page. I thought we said that templates are not limited to specific clients or groups.

**Comment by bpdesigns** [comment]
![screen shot 2016-07-26 at 10 35 54 pm](https://cloud.githubusercontent.com/assets/15329140/17163986/56cc3edc-5381-11e6-91c9-11f5f2861a8b.png)
Same comment for "edit template" page

**Comment by kuanb** [comment]
Has been removed on create views, will update tables accordingly

**Comment by kuanb** [comment]
Has been removed on create views, will update tables accordingly

**Comment by kuanb** [comment]
36d60dd..8c429bd resolved
