### ISSUE TITLE
Update flow after picking a template. 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#128]
@kuanb we didn't really discuss this but here is my though

![screen shot 2016-07-26 at 10 35 54 pm](https://cloud.githubusercontent.com/assets/15329140/17164173/d2cd52ae-5382-11e6-8680-d8c684159439.png)
![screen shot 2016-07-26 at 10 36 54 pm](https://cloud.githubusercontent.com/assets/15329140/17164174/d52895a4-5382-11e6-8f83-ec9fbe1d6e16.png)

Instead of these two pages back to back I propose creating one page. See Below:
![write to](https://cloud.githubusercontent.com/assets/15329140/17164181/e8205e62-5382-11e6-9a77-6620c9f47563.jpg)

Note: text updates: Choose a Client / Choose a contact method

**Comment by kuanb** [comment]
ok this is a tad complex... will do post other pressing items if time permits

**Comment by bpdesigns** [comment]
sounds good

**Comment by kuanb** [comment]
this is pre-v4. new workflow proposals have been moved to https://github.com/slco-2016/clientcomm/issues/242
