### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#13]
Show data on who’s using the tool:
- measure how many clients and conversations are being created 
- what types of messages are being sent,
- the number of messages in conversation and the 
- length of time between a conversation start and close 

(based on notes from Kele)

**Comment by kuanb** [comment]
From Kele: 

If possible, I’d like to know:
·        How many clients have responded back

·        Can we tell if the number isn’t valid? (they gave us a fake number)

·        A break out of staff name and # of messages (to see the high utilizers of the system?).  We can use the data to see if clients are completing successfully or initiating based on reminders.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14291618/2fde5514-fb19-11e5-8896-27d6799b030c.png)

here's just the # of msgs being sent in a day... should also break down further by inbound or outbound, etc....

**Comment by kuanb** [comment]
I think we need to break down each of the imrpovements into separate issues as we measured out during metrics discussion today. Going to close this one as it is high level

**Comment by bpdesigns** [comment]
I agree

On Mon, May 2, 2016 at 5:02 PM, Kuan Butts <notifications@github.com> wrote:

> I think we need to break down each of the imrpovements into separate
> issues as we measured out during metrics discussion today. Going to close
> this one as it is high level
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/slco-2016/clientcomm/issues/13#issuecomment-216399880>
>



-- 
*Join me at the Code for America Summit
<https://www.codeforamerica.org/summit/?source_codes=staff>, November 1 -
3, 2016. *

Ben Peterson // Designer, 2016 *Code for America Fellow
<http://www.codeforamerica.org/geeks/fellowship-apply/?source_codes=staff> *
// (385) 202-5458 // *@bpdesign <https://twitter.com/bpdesign>*
