### ISSUE TITLE
Make departments set-able by admins in an org

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#132]
Three clientcomm phone numbers

1. **support account**-assessment and presentence unit (first interaction with client?) 
- needs to view all clients on case manager loads (I believe they already have access to case manager case loads through ctracks.
- need access to add and remove clients from case managers case load 
- they need to create and send notifications on behalf of case managers to their new clients to set up initial appointments

other thoughts for features for support role:
A. maybe there needs to be an alert in clientcomm letting case managers know that they have a new client or that client has been removed 
B. maybe support or admin has the ability to create organization wide templates

2. **case managers** (pretrial/probation) keep the number we already have.

3. **therapists / ISP officers** they keep tabs on clients, have meetings with them. they need a separate phone number so clients are not texting both their therapists and case managers with the same number

**Comment by bpdesigns** [comment]
@kuanb should the details for features of the "support account" be broken down further into separate issues? Happy do so if that is helpful

**Comment by kuanb** [comment]
v4 supports and support acct has evolved
