### ISSUE TITLE
Admin page - department separation 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#142]
Maybe we should have a dropdown instead of fill in to determine department and position. 

Why? 
- Addresses typing errors 
- will come in handy when we roll out multiple numbers to be sure they are given to the right people
- we have case managers and therapists under the same heading.

See:
We have 3 sections for Probation. One is just incorrectly spelled, one is an elaboration on the title Probation. 

![screen shot 2016-08-05 at 12 37 30 pm](https://cloud.githubusercontent.com/assets/15329140/17448506/932a4e48-5b09-11e6-9047-2ace0828f33a.png)

 case manager and therapist under the same heading.

![screen shot 2016-08-05 at 12 42 26 pm](https://cloud.githubusercontent.com/assets/15329140/17448613/16608b06-5b0a-11e6-8860-1a610ed2e1f9.png)

**Comment by kuanb** [comment]
Departments are separated in V4 and in current admin view
