### ISSUE TITLE
Unread notifications

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#15]

**Comment by kuanb** [comment]
Moved from title: highlight in client list the ones who have open messages waiting for a response

![image](https://cloud.githubusercontent.com/assets/6053396/14312932/792b74e2-fba3-11e5-9b13-e6747cf5d1ba.png)
^ Implemented

**Comment by kuanb** [comment]
mostly resolved via https://github.com/slco-2016/clientcomm/commit/820d413ad8b0cc468d941bff879736e4412146f4
