### ISSUE TITLE
limit messages out to 160 chars and truncate if somehow submitted > than 160

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#16]

**Comment by kuanb** [comment]
Resolved via c736d187be87edacdaba16b7a04e622d174bbbe6

**Comment by kuanb** [comment]
Issue was not resolved, that was only to the /sms POST endpoint, but fails to accommodate for user input on cm response

**Comment by bpdesigns** [comment]
Rather than truncate a message over 160 characters, what about generating a pop up message and disabling the send button after 160 is reached?

@kuanb This also raises the question if we should limit emails to the same length so that the message rules don't change when the delivery method changes.

**Comment by kuanb** [comment]
Ben that will be a front end feature. This has to do with mechanics of the internal POST API. We can add responsive UX features, too. I've already limited the text box to 160 chars.

**Comment by kuanb** [comment]
commit d9a445794e203b23c93eedc3a72d1f197f7ed9e2
commit 726e4bcc71c4a81739e2e1d68af5fbccf4425067
commit b8051bed1e0376bec58cff45abb82dc20ffa968e

resolved via ^
