### ISSUE TITLE
Security on Twilio posts? Some sort of Twilio log in so random people are not making POSTs?

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#189]

**Comment by maxmcd** [comment]
https://www.twilio.com/docs/api/security#validating-requests

**Comment by kuanb** [comment]
Oh, wow, cool. So just need to implement that when receiving and SMS at that endpoint.

**Comment by kuanb** [comment]
https://github.com/slco-2016/clientcomm/commit/5e5373f78b78ac1fd54da408964c70e9414dc525 should address. still awaiting tests to confirm

**Comment by kuanb** [comment]
https://github.com/slco-2016/clientcomm/commit/12970a5a633a9d0d1625002e0125f3cd71259ce7 closes this sucker out. tests clearing with set header added to old tests and new one designed to 403 with no twilio header set

**Comment by kuanb** [comment]
https://github.com/slco-2016/clientcomm/commit/c949cb27d76a1981fb93733e8f4f0ad1bd626859 fixes hanging missing test that did not have header set
