### ISSUE TITLE
Issue with clients having more than one of same commconn open.

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#210]
![image](https://cloud.githubusercontent.com/assets/6053396/19737948/68e7be94-9b6a-11e6-838f-967df9ff495e.png)

Example with a client of Gary Wood. Solution: Make sure to close and not allow repeat comm methods per client-case manager combination.

**Comment by bpdesigns** [comment]
good catch!

**Comment by kuanb** [comment]
Was able to identify when trying to pair in c tracks data

**Comment by kuanb** [comment]
This issue continues to this day and needs to be resolved asap.

**Comment by kuanb** [comment]
Redundant issue was created 
https://github.com/slco-2016/clientcomm/issues/235

Here was text: 
Issue is caused because when a phone number is edited and something is changed about it, the old number is removed and instead of the closed date being null, it has a datetime.

When numbers are retrieved, it does not account for whether they are still active or not, so you end up with duplicate numbers rendering in the conversation... So I think if a number is updated in name and the communication id that it references stays the same, then it should just be updated, not "fully" replaced.

**Comment by kuanb** [comment]
e9915bd..fc3c70d introduces tests to make sure that the update on an existing commconn works well... we still need to make sure that on the left join the repeats on the contact methods does not occur

**Comment by kuanb** [comment]
Resolved via 42b37ef..fadcae1
