### ISSUE TITLE
Add a usage gauge for case managers to track their usage vs the group

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#212]

**Comment by kuanb** [comment]
Resolved via

https://github.com/slco-2016/clientcomm/commit/b1997b4ba77c64724005f82510c3bbd7ea81972c

https://github.com/slco-2016/clientcomm/commit/48b72e4d4bbfeef6c874afae7bf1bd8b923572a6

https://github.com/slco-2016/clientcomm/commit/48b72e4d4bbfeef6c874afae7bf1bd8b923572a6

https://github.com/slco-2016/clientcomm/commit/e963c5fca23f3ae66920830d40ba94ce5ad128ed

**Comment by kuanb** [comment]
Still need to have some sort of mini view at admin level

Looks like this for primary users:
![image](https://cloud.githubusercontent.com/assets/6053396/19876798/d38f1b90-9f96-11e6-9d1e-5b5aee162442.png)


Wanted for admin users is something more small:
![image](https://cloud.githubusercontent.com/assets/6053396/19876808/dd525dcc-9f96-11e6-95ee-88335b749f31.png)

**Comment by kuanb** [comment]
These have been implemented in production.
