### ISSUE TITLE
Color group page, Workflow improvements - adding new colors 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#220]
button placement is confusing. hard to know what to click to save a color. 

Action confusion: "do I click the plus sign or save and continue?"

![screen shot 2016-11-02 at 11 24 12 am](https://cloud.githubusercontent.com/assets/15329140/19942923/8a1ba6b0-a0f2-11e6-897e-45233682d373.png)

**Comment by bpdesigns** [comment]
Also its a little surprising that "save and continue" sends you to the client page.

Possible solution would be to change text from "save & continue" to just "continue"

**Comment by kuanb** [comment]
434c0a5..7a7b3c8 resolves.
