### ISSUE TITLE
Rows in "departments" page should be clickable and allow you to drill down to a specific department like you can from the side nav from the "dashboard" page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#221]
![screen shot 2016-11-02 at 11 56 18 am](https://cloud.githubusercontent.com/assets/15329140/19943145/67a929ee-a0f3-11e6-8901-219dd74b6fbf.png)

**Comment by kuanb** [comment]
f0fec9c..434c0a5 resolves this and adds filter so when looking at one dept not all are avaialble
