### ISSUE TITLE
Text Change - "schedule notifications" page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#222]
Replace "Create text message" with "write message"
Replace "Create audio message" with "audio message"

![screen shot 2016-11-08 at 12 30 28 pm](https://cloud.githubusercontent.com/assets/15329140/20116207/40e4da4e-a5b0-11e6-8d5d-b17c55208893.png)

**Comment by kuanb** [comment]
673c23f..f0fec9c resolves
