### ISSUE TITLE
Client Details Page - Phase 2 idea

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#23]
Create a profile page for each client to allow case manager to view relevant details about their client while crafting text messages to send to them 
- possibly have clientcomm pull from c-track or other source
- include photo of client

**Comment by kuanb** [comment]
@bpdesigns this is effectively what we were discussing today with the admin brief view/overview of a client

**Comment by bpdesigns** [comment]
we have a client profile that is a separate page. Good enough I think.
