### ISSUE TITLE
Enable email messaging as an option in the communication stream

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#29]

**Comment by kuanb** [comment]
So right now we just have a pill for text, we should have pills for voice and email as well.

**Comment by kuanb** [comment]
im amazed this is so old.... ! 

f9172ce..ea1094a resolves :)

![image](https://cloud.githubusercontent.com/assets/6053396/20910141/8d22534a-bb14-11e6-9d56-fb8c753f0fc1.png)

reference image
