### ISSUE TITLE
transcripts are cluttered with metadata and hard to read

### ISSUE THREAD

**Issue by tmaybe** [slco-2016/clientcomm#354]
Currently each message in a transcript takes up 10 lines and includes: message & conversation ID, cell # and device type, read by user: true/false, sent by client: true/false, the case manager's name, status, date created, date transcript downloaded, and local timezone.

We should figure out which metadata are critical and remove everything else, and reduce repetition for elements that don't/rarely change.

**Comment by tmaybe** [comment]
This was prompted by feedback from a case manager using the app in SLCO.

**Comment by alsomanya** [comment]
Based on what we heard, my suggestion would be to keep the following:
- Date & time of message creation
- Content of message
- Sent by user (true/false)
- Status (delivered / queued / etc)
- Communication method (i.e. "Burner - 123-456-7890)
