### ISSUE TITLE
"Click to view new message" notification doesn't go anywhere

### ISSUE THREAD

**Issue by alsomanya** [slco-2016/clientcomm#384]
**Steps to replicate:**
1. As a case manager, I receive a new message from a client
2. I click on the alert in my top nav
3. I click the prompt to view the message

**Expected result:**
I'm taken to the new message in the message stream with my client. 

**Actual result:**
I stay on the list of my clients in an endless loop until I click on the right client. 

![new message notification](https://cloud.githubusercontent.com/assets/5083453/24631674/0b7673fc-1876-11e7-917d-5bb203eb68f7.gif)

**Comment by tmaybe** [comment]
What should the behavior be if the case manager has new messages from more than one client? Some options:

- There are multiple notifications, one for each client with unread messages, and clicking the notification takes you to that client's message stream.
- There's a single notification, and clicking it takes you to the message stream of the client with the oldest unread messages
- There's a single notification, and if there's more than one client with unread messages, it takes you to the client list (current behavior), but if there's only one client with unread messages, it takes you to that client's message stream.

**Comment by alsomanya** [comment]
@tmaybe what's the difference between those three options in terms of cost / complexity?

**Comment by tmaybe** [comment]
They're all roughly similar in cost; the multiple notifications one might be more complex (and it's my least favorite from a UX perspective).

**Comment by alsomanya** [comment]
In that case, I think I prefer the last option (and once we incorporate a suggestion like #400 the unreads will be at the top). Possible to change the message of the alert if there are multiple notifications to say "You have new unread messages. Click here to view them."

Also, I assume this only happens if there are multiple notifications from _different_ clients, right? If one client sends multiple messages, clicking the alert should take a user to the message stream of that client.

**Comment by tmaybe** [comment]
Yes, we can change the message if there are multiple messages. And agreed, if a single client has multiple new messages, it should take you to that client's message stream.
