### ISSUE TITLE
Voice URL endpoint needs to exist and have response.

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#51]
Response should at this time indicate this is text only service and they need to text in if they want to use the service.

**Comment by bpdesigns** [comment]
How about: "Currently, this is a text only number. Voice option will added at a future date. Please dial 385-468-3500 for the front desk and ask for your case manager. Thank you."

**Comment by kuanb** [comment]
Sounds good.

**Comment by kuanb** [comment]
resolved via https://github.com/slco-2016/clientcomm/commit/fb3d69d500c21357d648a1dd4ec2152b5ecd1cee

**Comment by kuanb** [comment]
Put into production as of 3:10 PST Monday
