### ISSUE TITLE
Add exit button on pages for adding and editing new contacts and clients

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#54]

**Comment by kuanb** [comment]
basically an exit button from card... i am gonna do an "X" in upper right hand corner

**Comment by kuanb** [comment]
o nvm i just saw on sketch file

![image](https://cloud.githubusercontent.com/assets/6053396/15277343/13f24290-1ab6-11e6-9a23-2bc7c3340642.png)

**Comment by kuanb** [comment]
added
