### ISSUE TITLE
Success alert in closed conversation -update text in message

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#55]
![screen shot 2016-05-15 at 11 49 33 am](https://cloud.githubusercontent.com/assets/15329140/15276208/4dc68668-1a96-11e6-91c2-90362eaad8d3.png)

Alert reads "Success: closed conversation" when opening a closed conversation. 

Should read "Success: conversation reopened"

**Comment by kuanb** [comment]
awesome catch
