### ISSUE TITLE
Add a client - optional vs. required 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#56]
I think Date of Birth Be should not be optional— I think we should capture that. Its easy info and will help track clients.

Question: Do you think middle name should be required? (is it because its necessary to distinguish between clients?)

**Comment by kuanb** [comment]
Middle name i snot necessary and is not consistently captured in CTracks. As a result, we should not have it be mandatory. Understood re: DOB - let's talk to Dave about that and make sure that this is something they can "rely" on. If they can't, then forcing capture could result in people entering false dates which would be worse than no dates at all.
