### ISSUE TITLE
Line length in messages - Force them to spilt lines

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#58]
Not high priority but I tried creating a looooong word in a message and it over ran the box. 

Suggestion: force line to split after certain # of characters. 
![screen shot 2016-05-15 at 11 53 54 am](https://cloud.githubusercontent.com/assets/15329140/15276267/13e09626-1a98-11e6-8140-19cf5a12d52b.png)

**Comment by kuanb** [comment]
ah yeah i caught that too! :) resolved
