### ISSUE TITLE
Alert Messages: tone of message 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#59]
Instead of saying "Alert: No access allowed, not logged in" I think we should try a friendly tone. This is important because it essentially the tool talking to a case manager and impacts how they feel about using it. 

I would lose "Alert" altogether and make the messages more conversational. ex. "Please log in for access"

![screen shot 2016-05-15 at 11 56 12 am](https://cloud.githubusercontent.com/assets/15329140/15276281/3f36eadc-1a98-11e6-8ba0-b17fcdbddd21.png)

**Comment by kuanb** [comment]
updated

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/15277240/2cad9fa8-1ab3-11e6-8cdf-4bbc8fda6a74.png)
