### ISSUE TITLE
Describing open conversations in conversation stream

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#6]
![screen shot 2016-03-23 at 3 10 11 pm](https://cloud.githubusercontent.com/assets/15329140/14000992/67075fc8-f109-11e5-8404-5c635900afc4.png)
In the list of conversations (see attached) I think it would be clearer to label this as "open" rather than "new."

**Comment by bpdesigns** [comment]
@kuanb let me know if this makes sense to you.

**Comment by kuanb** [comment]
In general, this view needs to be cleaned up. Agreed.

**Comment by kuanb** [comment]
Difference between this and last one? https://github.com/slco-2016/clientcomm/issues/5

Could both be combined?

**Comment by bpdesigns** [comment]
Yes.

**Comment by kuanb** [comment]
Combined and closed
