### ISSUE TITLE
Conversations page - Line length of subject field

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#60]
Line splits when subject of message gets over a certain length.

Suggestions:
1) make the line length of the field longer by shifting over "comm method"
2) hide message beyond certain length but cutting it short and adding "..." to the end of line. 
![screen shot 2016-05-15 at 11 57 56 am](https://cloud.githubusercontent.com/assets/15329140/15276309/0cff45ea-1a99-11e6-9ae0-bad3c11d4820.png)

**Comment by kuanb** [comment]
There is a length limit to convos that is 70 characters (I believe that is specific #). Either way, there is no need to have comm method be so wide so I reduced the width of comm method and now conversation should not have any issues
