### ISSUE TITLE
Button presence - "archived /current" and "conversations/contacts"

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#61]
Looking at these pages now I think these buttons need to stand out more.

Suggestions:
1) change white pill color to medium or dark blue
2) increase scale of buttons 

![screen shot 2016-05-15 at 11 59 55 am](https://cloud.githubusercontent.com/assets/15329140/15276310/1c56174e-1a99-11e6-8485-16676de3ca27.png)
![screen shot 2016-05-15 at 11 57 56 am](https://cloud.githubusercontent.com/assets/15329140/15276319/413c43ee-1a99-11e6-89fc-889ddb8ef715.png)

**Comment by bpdesigns** [comment]
Updated on sketch on "client list" page 
![screen shot 2016-05-15 at 12 50 20 pm](https://cloud.githubusercontent.com/assets/15329140/15276393/a37ea450-1a9b-11e6-9f65-2267d2931959.png)

**Comment by kuanb** [comment]
good point, done
