### ISSUE TITLE
Check for messages - add interactivity

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#62]
"Check for messages" button changes states on hover. However nothing changes when clicked, so there is not visual indication that you actually refreshed the page. 

Suggestion: on click change button color to white

**Comment by kuanb** [comment]
OK - So the background changes to white when clicked? 
What happens after? The page will refresh and the style will return to the original blue background (or actually no background just the background of the navbar).

**Comment by bpdesigns** [comment]
The color change on hover happens with the text and icon. Color change on click should be on text and icon as well to match. 

After click I thought it would make sense for the text to return to the active original state signaling that it is clickable

**Comment by kuanb** [comment]
resolved with new async method
