### ISSUE TITLE
Alert / success indications at the top of page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#63]
Right now it is noticeable but the scale of it blends in to much with the page. I think it should be more distinct. 

Suggestions:
1) I would increase the height of the alert box to 60-70px high at the top of page so it is visually more prominent. 
2) change the font color to black

**Comment by kuanb** [comment]
black looked strange, went with white

![image](https://cloud.githubusercontent.com/assets/6053396/15277268/b1fd55e0-1ab3-11e6-9484-07a28ad8dd43.png)

**Comment by kuanb** [comment]
made font bigger in lieu of black

**Comment by kuanb** [comment]
alternative

![image](https://cloud.githubusercontent.com/assets/6053396/15277273/d1d74c9a-1ab3-11e6-973c-a20c5ab14ae6.png)

**Comment by kuanb** [comment]
reopen if you want to discuss black with the smaller text
