### ISSUE TITLE
Add migration to incl "status" col val in messages table

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#88]
with string values “failed” “success” “…"

**Comment by kuanb** [comment]
Really wondering if this is necessary... Except if we want to eval how many messages fail to send. This would be something we do if resending once does not work.

Would log that failure to col as well as send email notifying case manager.

**Comment by bpdesigns** [comment]
How often does this happen?

On Fri, Jul 8, 2016 at 1:59 PM, Kuan Butts <notifications@github.com> wrote:

> Really wondering if this is necessary... Except if we want to eval how
> many messages fail to send. This would be something we do if resending once
> does not work.
>
> Would log that failure to col as well as send email notifying case manager.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/slco-2016/clientcomm/issues/88#issuecomment-231471348>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOnndAaegx9C7de5lM0wf4-dhMI1yozmks5qTro6gaJpZM4I8Ebg>
> .
>



-- 
*Join me at the Code for America Summit
<https://www.codeforamerica.org/summit/?source_codes=staff>, November 1 -
3, 2016. *

Ben Peterson // Designer, 2016 *Code for America Fellow
<http://www.codeforamerica.org/geeks/fellowship-apply/?source_codes=staff> *
// (385) 202-5458 // *@bpdesign <https://twitter.com/bpdesign>*

**Comment by kuanb** [comment]
Infrequently... it'll happen if someone writes a long textt that gets packaged and sent in packets. There are a few clients that write very long text responses

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 8, 2016 at 5:45 PM, bpdesigns<notifications@github.com> wrote:   How often does this happen?

On Fri, Jul 8, 2016 at 1:59 PM, Kuan Butts <notifications@github.com> wrote:

> Really wondering if this is necessary... Except if we want to eval how
> many messages fail to send. This would be something we do if resending once
> does not work.
>
> Would log that failure to col as well as send email notifying case manager.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/slco-2016/clientcomm/issues/88#issuecomment-231471348>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOnndAaegx9C7de5lM0wf4-dhMI1yozmks5qTro6gaJpZM4I8Ebg>
> .
>



-- 
*Join me at the Code for America Summit
<https://www.codeforamerica.org/summit/?source_codes=staff>, November 1 -
3, 2016. *

Ben Peterson // Designer, 2016 *Code for America Fellow
<http://www.codeforamerica.org/geeks/fellowship-apply/?source_codes=staff> *
// (385) 202-5458 // *@bpdesign <https://twitter.com/bpdesign>*

**Comment by kuanb** [comment]
Questioning the relevance of this, given we use `tw_status`....
