### ISSUE TITLE
Clicking on client name from "Client List" takes you right into the most recent conversation

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#95]
Instead of clicking on client name from "Client List" leading to the "Client Page" have that link take you into the most recent conversation with the client or starts a new conversation if there are no open conversation.

Why?
This removes an extra step to starting to message with clients.

**Comment by kuanb** [comment]
Confirmed: both go to latest conversation.

**Comment by kuanb** [comment]
resolved 5dc1bfb..9791244
