### ISSUE TITLE
Remove "Client Page" link when already on client page. 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#96]
During the last trip. I saw multiple case managers try to click on this button from the "client page" 

![screen shot 2016-07-05 at 1 24 31 pm](https://cloud.githubusercontent.com/assets/15329140/16598723/1f567d9c-42b4-11e6-8ee7-173ef9b654bb.png)

Why?
Its causing confusion and hopefully and easy fix.

**Comment by kuanb** [comment]
Or it should be highlighted. Confusing it exists when you are on the page that is "it."

**Comment by kuanb** [comment]
6f8fceb..5dc1bfb resolved
