### ISSUE TITLE
Wording updates

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#97]
"Add a Client" = "Add New Client"
“Client list” = "Client Directory" 
"Capture Board" = "Unknown Client Board"
 
![screen shot 2016-07-05 at 1 30 24 pm 1](https://cloud.githubusercontent.com/assets/15329140/16598881/d35cc594-42b4-11e6-9d87-7df1feaa3eb3.png)

“contacts” = “contact method” 
"new contact" = "add contact method"
![contacts](https://cloud.githubusercontent.com/assets/15329140/16599210/25a93eb2-42b6-11e6-9341-0cc1f3b18ff4.jpg)

“Archive” = "Close Case" ( archive "it’s like deleting an email." / "ctrack says 'case closed'” )

![archive](https://cloud.githubusercontent.com/assets/15329140/16599216/2c10052e-42b6-11e6-9a78-99e05a1db99f.jpg)

**Comment by kuanb** [comment]
"Unclaimed Messages"

**Comment by kuanb** [comment]
096386b..7723b84 resolved
