### ISSUE TITLE
Add client name to message screen - Some case managers are getting lost when interupted 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#98]
Its currently missing from the page

![clientname_on message_screen](https://cloud.githubusercontent.com/assets/15329140/16599297/8b3206f6-42b6-11e6-99fa-4a7e9b0ecccd.jpg)

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/16632076/3843212a-4377-11e6-8b30-020cc4acad21.png)


resolved on all pages by including client name up top in navbar

**Comment by bpdesigns** [comment]
@kuanb so the name shows before the subject? 

Can we visually distinguish the two? Ie, **Jazmin Lat**: contact
