### ISSUE TITLE
Add links to content from "All Clients" page, also called "Client List" (should update to "client directory"  per issue ... 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#99]
NOTE: "All Clients" page, is also called "Client List" (should update to "client directory"  per issue 97)

Interactivity for "all clients" / "notifications" / "templates" links should mimic "current clients" links. See image for button styles:
![screen shot 2016-07-05 at 1 46 49 pm](https://cloud.githubusercontent.com/assets/15329140/16599444/2acd4edc-42b7-11e6-9e86-70e57a2051a7.png)

**Comment by kuanb** [comment]
"Client Directory"
